export default sampleData = [
  {
    section: 'style',
    subsection: '',
    title: 'Jill Biden, Changing the Fashion Game',
    abstract:
      'Cheering the American Olympians, the first lady broke with recent sartorial customs.',
    url: 'https://www.nytimes.com/2021/07/26/style/jill-biden-olympics.html',
    uri: 'nyt://article/e3f08012-d543-5112-a134-96cf685ee1e3',
    byline: 'By Vanessa Friedman',
    item_type: 'Article',
    updated_date: '2021-07-26T14:18:40-04:00',
    created_date: '2021-07-26T08:45:23-04:00',
    published_date: '2021-07-26T08:45:23-04:00',
    material_type_facet: '',
    kicker: 'Critic’s notebook',
    des_facet: [
      'Sustainable Living',
      'Fashion and Apparel',
      'Olympic Games (2020)',
      'Politics and Government',
      'First Ladies (US)',
      'your-feed-fashion',
    ],
    org_facet: ['Narciso Rodriguez LLC', 'Polo Ralph Lauren Corp'],
    per_facet: [
      'Biden, Jill Tracy Jacobs',
      'Ford, Tom',
      'Kors, Michael',
      'Maxwell, Brandon (1984- )',
    ],
    geo_facet: [],
    multimedia: [
      {
        url: 'https://static01.nyt.com/images/2021/07/26/lens/26Jill-Olympics-01/merlin_191317311_846bb335-44c4-4e08-9cd4-3a5a65aec7cb-superJumbo.jpg',
        format: 'superJumbo',
        height: 1249,
        width: 2048,
        type: 'image',
        subtype: 'photo',
        caption:
          'Jill Biden wore pieces from the U.S. Olympics uniform by Ralph Lauren to watch the men’s 400-meter individual medley swim race in Tokyo.',
        copyright: 'Antonio Bronic/Reuters',
      },
      {
        url: 'https://static01.nyt.com/images/2021/07/26/lens/26Jill-Olympics-01/26Jill-Olympics-01-thumbStandard.jpg',
        format: 'Standard Thumbnail',
        height: 75,
        width: 75,
        type: 'image',
        subtype: 'photo',
        caption:
          'Jill Biden wore pieces from the U.S. Olympics uniform by Ralph Lauren to watch the men’s 400-meter individual medley swim race in Tokyo.',
        copyright: 'Antonio Bronic/Reuters',
      },
      {
        url: 'https://static01.nyt.com/images/2021/07/26/lens/26Jill-Olympics-01/26Jill-Olympics-01-thumbLarge.jpg',
        format: 'thumbLarge',
        height: 150,
        width: 150,
        type: 'image',
        subtype: 'photo',
        caption:
          'Jill Biden wore pieces from the U.S. Olympics uniform by Ralph Lauren to watch the men’s 400-meter individual medley swim race in Tokyo.',
        copyright: 'Antonio Bronic/Reuters',
      },
      {
        url: 'https://static01.nyt.com/images/2021/07/26/lens/26Jill-Olympics-01/26Jill-Olympics-01-mediumThreeByTwo210-v2.jpg',
        format: 'mediumThreeByTwo210',
        height: 140,
        width: 210,
        type: 'image',
        subtype: 'photo',
        caption:
          'Jill Biden wore pieces from the U.S. Olympics uniform by Ralph Lauren to watch the men’s 400-meter individual medley swim race in Tokyo.',
        copyright: 'Antonio Bronic/Reuters',
      },
      {
        url: 'https://static01.nyt.com/images/2021/07/26/lens/26Jill-Olympics-01/merlin_191317311_846bb335-44c4-4e08-9cd4-3a5a65aec7cb-articleInline.jpg',
        format: 'Normal',
        height: 116,
        width: 190,
        type: 'image',
        subtype: 'photo',
        caption:
          'Jill Biden wore pieces from the U.S. Olympics uniform by Ralph Lauren to watch the men’s 400-meter individual medley swim race in Tokyo.',
        copyright: 'Antonio Bronic/Reuters',
      },
    ],
    short_url: 'https://nyti.ms/3kTdmzj',
  },
  {
    section: 'fashion',
    subsection: '',
    title: 'Suddenly It’s Bare Season',
    abstract:
      'Bras in the parks, skivvies on Fifth Avenue: Is this the logical endpoint of increasingly blurred distinctions between public and private?',
    url: 'https://www.nytimes.com/2021/07/22/fashion/suddenly-its-bare-season.html',
    uri: 'nyt://article/9481999c-143c-582a-a48b-f780537559af',
    byline: 'By Guy Trebay',
    item_type: 'Article',
    updated_date: '2021-07-22T15:35:54-04:00',
    created_date: '2021-07-22T03:00:10-04:00',
    published_date: '2021-07-22T03:00:10-04:00',
    material_type_facet: '',
    kicker: 'Critic’s Notebook',
    des_facet: [
      'Quarantine (Life and Culture)',
      'Fashion and Apparel',
      'Women and Girls',
      'Lingerie and Underwear',
    ],
    org_facet: [],
    per_facet: [],
    geo_facet: ['New York City'],
    multimedia: [
      {
        url: 'https://static01.nyt.com/images/2021/07/22/fashion/22NAKEDCITY19/merlin_190844250_617b5c67-9612-4800-847c-28cb987c6b4b-superJumbo.jpg',
        format: 'superJumbo',
        height: 1358,
        width: 2048,
        type: 'image',
        subtype: 'photo',
        caption: '',
        copyright: 'Sara Messinger for The New York Times',
      },
      {
        url: 'https://static01.nyt.com/images/2021/07/22/fashion/22NAKEDCITY19/22NAKEDCITY19-thumbStandard.jpg',
        format: 'Standard Thumbnail',
        height: 75,
        width: 75,
        type: 'image',
        subtype: 'photo',
        caption: '',
        copyright: 'Sara Messinger for The New York Times',
      },
      {
        url: 'https://static01.nyt.com/images/2021/07/22/fashion/22NAKEDCITY19/22NAKEDCITY19-thumbLarge.jpg',
        format: 'thumbLarge',
        height: 150,
        width: 150,
        type: 'image',
        subtype: 'photo',
        caption: '',
        copyright: 'Sara Messinger for The New York Times',
      },
      {
        url: 'https://static01.nyt.com/images/2021/07/22/fashion/22NAKEDCITY19/22NAKEDCITY19-mediumThreeByTwo210.jpg',
        format: 'mediumThreeByTwo210',
        height: 140,
        width: 210,
        type: 'image',
        subtype: 'photo',
        caption: '',
        copyright: 'Sara Messinger for The New York Times',
      },
      {
        url: 'https://static01.nyt.com/images/2021/07/22/fashion/22NAKEDCITY19/merlin_190844250_617b5c67-9612-4800-847c-28cb987c6b4b-articleInline.jpg',
        format: 'Normal',
        height: 126,
        width: 190,
        type: 'image',
        subtype: 'photo',
        caption: '',
        copyright: 'Sara Messinger for The New York Times',
      },
    ],
    short_url: 'https://nyti.ms/3zlQLPM',
  },
  {
    section: 'movies',
    subsection: '',
    title: '‘Old’ Review: They Say Sun Can Age You, but This Is Ridiculous',
    abstract:
      'A half-hour at the beach costs vacationers a year in this disquieting new horror puzzler, written and directed by M. Night Shyamalan.',
    url: 'https://www.nytimes.com/2021/07/22/movies/old-review.html',
    uri: 'nyt://article/e051deee-dab7-54ac-ab25-395739bb5d82',
    byline: 'By Glenn Kenny',
    item_type: 'Article',
    updated_date: '2021-07-23T01:08:07-04:00',
    created_date: '2021-07-22T12:18:36-04:00',
    published_date: '2021-07-22T12:18:36-04:00',
    material_type_facet: '',
    kicker: '',
    des_facet: ['Movies', 'Old (Movie)'],
    org_facet: [],
    per_facet: ['Garcia Bernal, Gael', 'Krieps, Vicky', 'Shyamalan, M Night'],
    geo_facet: [],
    multimedia: [
      {
        url: 'https://static01.nyt.com/images/2021/07/22/arts/22old1/22old1-superJumbo.jpg',
        format: 'superJumbo',
        height: 1152,
        width: 2048,
        type: 'image',
        subtype: 'photo',
        caption:
          'Gael García Bernal and Vicky Krieps realize there’s something off about their secluded beach vacation spot in “Old.”',
        copyright: 'Universal Pictures',
      },
      {
        url: 'https://static01.nyt.com/images/2021/07/22/arts/22old1/22old1-thumbStandard.jpg',
        format: 'Standard Thumbnail',
        height: 75,
        width: 75,
        type: 'image',
        subtype: 'photo',
        caption:
          'Gael García Bernal and Vicky Krieps realize there’s something off about their secluded beach vacation spot in “Old.”',
        copyright: 'Universal Pictures',
      },
      {
        url: 'https://static01.nyt.com/images/2021/07/22/arts/22old1/22old1-thumbLarge.jpg',
        format: 'thumbLarge',
        height: 150,
        width: 150,
        type: 'image',
        subtype: 'photo',
        caption:
          'Gael García Bernal and Vicky Krieps realize there’s something off about their secluded beach vacation spot in “Old.”',
        copyright: 'Universal Pictures',
      },
      {
        url: 'https://static01.nyt.com/images/2021/07/22/arts/22old1/22old1-mediumThreeByTwo210.jpg',
        format: 'mediumThreeByTwo210',
        height: 140,
        width: 210,
        type: 'image',
        subtype: 'photo',
        caption:
          'Gael García Bernal and Vicky Krieps realize there’s something off about their secluded beach vacation spot in “Old.”',
        copyright: 'Universal Pictures',
      },
      {
        url: 'https://static01.nyt.com/images/2021/07/22/arts/22old1/22old1-articleInline.jpg',
        format: 'Normal',
        height: 107,
        width: 190,
        type: 'image',
        subtype: 'photo',
        caption:
          'Gael García Bernal and Vicky Krieps realize there’s something off about their secluded beach vacation spot in “Old.”',
        copyright: 'Universal Pictures',
      },
    ],
    short_url: 'https://nyti.ms/3eHSXJG',
  },
  {
    section: 'realestate',
    subsection: '',
    title: '$2 Million Homes in California',
    abstract:
      'A storybook cottage in Los Angeles, a contemporary home in Long Beach and a Victorian in San Francisco.',
    url: 'https://www.nytimes.com/2021/07/26/realestate/Home-prices-california.html',
    uri: 'nyt://article/67985ad7-bb7c-5776-86a0-590e9a7df204',
    byline: 'By Angela Serratore',
    item_type: 'Article',
    updated_date: '2021-07-26T10:00:18-04:00',
    created_date: '2021-07-26T10:00:18-04:00',
    published_date: '2021-07-26T10:00:18-04:00',
    material_type_facet: '',
    kicker: 'What you Get',
    des_facet: [
      'Real Estate and Housing (Residential)',
      'Content Type: Service',
    ],
    org_facet: [],
    per_facet: [],
    geo_facet: [
      'Long Beach (Calif)',
      'San Francisco (Calif)',
      'Los Angeles (Calif)',
    ],
    multimedia: [
      {
        url: 'https://static01.nyt.com/images/2021/07/26/realestate/26WYG-CA-slide-7168/26WYG-CA-slide-7168-superJumbo.jpg',
        format: 'superJumbo',
        height: 1362,
        width: 2048,
        type: 'image',
        subtype: 'photo',
        caption: '',
        copyright: 'Luan Pernia',
      },
      {
        url: 'https://static01.nyt.com/images/2021/07/26/realestate/26WYG-CA-slide-7168/26WYG-CA-slide-7168-thumbStandard.jpg',
        format: 'Standard Thumbnail',
        height: 75,
        width: 75,
        type: 'image',
        subtype: 'photo',
        caption: '',
        copyright: 'Luan Pernia',
      },
      {
        url: 'https://static01.nyt.com/images/2021/07/26/realestate/26WYG-CA-slide-7168/26WYG-CA-slide-7168-thumbLarge.jpg',
        format: 'thumbLarge',
        height: 150,
        width: 150,
        type: 'image',
        subtype: 'photo',
        caption: '',
        copyright: 'Luan Pernia',
      },
      {
        url: 'https://static01.nyt.com/images/2021/07/26/realestate/26WYG-CA-slide-7168/26WYG-CA-slide-7168-mediumThreeByTwo210.jpg',
        format: 'mediumThreeByTwo210',
        height: 140,
        width: 210,
        type: 'image',
        subtype: 'photo',
        caption: '',
        copyright: 'Luan Pernia',
      },
      {
        url: 'https://static01.nyt.com/images/2021/07/26/realestate/26WYG-CA-slide-7168/26WYG-CA-slide-7168-articleInline.jpg',
        format: 'Normal',
        height: 126,
        width: 190,
        type: 'image',
        subtype: 'photo',
        caption: '',
        copyright: 'Luan Pernia',
      },
    ],
    short_url: 'https://nyti.ms/3i4RmQf',
  },
  {
    section: 'style',
    subsection: '',
    title: '‘The Hot Doctor’ Finds a Life Partner Close to Home',
    abstract:
      'It took Dr. Ryan Weight almost a year to ask Jerri Hobdy out on a date. However, it only took one bubble tea outing to solidify their connection.',
    url: 'https://www.nytimes.com/2021/07/23/style/jerri-hobdy-ryan-weight-wedding.html',
    uri: 'nyt://article/1f2bed40-547a-5e1b-bd19-1462208e3b51',
    byline: 'By Jenny Block',
    item_type: 'Article',
    updated_date: '2021-07-26T16:13:35-04:00',
    created_date: '2021-07-23T05:00:16-04:00',
    published_date: '2021-07-23T05:00:16-04:00',
    material_type_facet: '',
    kicker: 'mini-vows',
    des_facet: ['Weddings and Engagements'],
    org_facet: [],
    per_facet: [],
    geo_facet: [],
    multimedia: [
      {
        url: 'https://static01.nyt.com/images/2021/07/25/fashion/00MINI-HobdyWeight/00MINI-HobdyWeight-superJumbo.jpg',
        format: 'superJumbo',
        height: 853,
        width: 1280,
        type: 'image',
        subtype: 'photo',
        caption: '',
        copyright: 'Michael Ash Smith',
      },
      {
        url: 'https://static01.nyt.com/images/2021/07/25/fashion/00MINI-HobdyWeight/00MINI-HobdyWeight-thumbStandard.jpg',
        format: 'Standard Thumbnail',
        height: 75,
        width: 75,
        type: 'image',
        subtype: 'photo',
        caption: '',
        copyright: 'Michael Ash Smith',
      },
      {
        url: 'https://static01.nyt.com/images/2021/07/25/fashion/00MINI-HobdyWeight/00MINI-HobdyWeight-thumbLarge.jpg',
        format: 'thumbLarge',
        height: 150,
        width: 150,
        type: 'image',
        subtype: 'photo',
        caption: '',
        copyright: 'Michael Ash Smith',
      },
      {
        url: 'https://static01.nyt.com/images/2021/07/25/fashion/00MINI-HobdyWeight/00MINI-HobdyWeight-mediumThreeByTwo210.jpg',
        format: 'mediumThreeByTwo210',
        height: 140,
        width: 210,
        type: 'image',
        subtype: 'photo',
        caption: '',
        copyright: 'Michael Ash Smith',
      },
      {
        url: 'https://static01.nyt.com/images/2021/07/25/fashion/00MINI-HobdyWeight/00MINI-HobdyWeight-articleInline.jpg',
        format: 'Normal',
        height: 127,
        width: 190,
        type: 'image',
        subtype: 'photo',
        caption: '',
        copyright: 'Michael Ash Smith',
      },
    ],
    short_url: 'https://nyti.ms/3Bzreo4',
  },
  {
    section: 'us',
    subsection: '',
    title:
      'After Covid Diagnosis, a Conservative Radio Host Sends a New Message',
    abstract:
      'The Tennessee radio host, Phil Valentine, said he was among those who did not need to get vaccinated. Now his struggle with the virus is sparking its own discussion.',
    url: 'https://www.nytimes.com/2021/07/25/us/phil-valentine-covid-nashville-.html',
    uri: 'nyt://article/00058803-fa8b-5587-ad35-0a2852c9fbdd',
    byline: 'By Hamilton Matthew Masters and Giulia Heyward',
    item_type: 'Article',
    updated_date: '2021-07-26T13:28:30-04:00',
    created_date: '2021-07-25T19:57:55-04:00',
    published_date: '2021-07-25T19:57:55-04:00',
    material_type_facet: '',
    kicker: '',
    des_facet: [
      'Vaccination and Immunization',
      'Coronavirus (2019-nCoV)',
      'Radio',
      'Rumors and Misinformation',
    ],
    org_facet: [],
    per_facet: ['Jahangir, Alex', 'Valentine, Phil (1959- )'],
    geo_facet: [],
    multimedia: [
      {
        url: 'https://static01.nyt.com/images/2021/07/25/lens/25nashville-photo/25nashville-photo-superJumbo.jpg',
        format: 'superJumbo',
        height: 1365,
        width: 2048,
        type: 'image',
        subtype: 'photo',
        caption:
          'Phil Valentine, a conservative radio show host, recording a podcast with his adult son, Campbell, in 2019.',
        copyright: 'Shelley Mays/The Tennessean',
      },
      {
        url: 'https://static01.nyt.com/images/2021/07/25/lens/25nashville-photo/25nashville-photo-thumbStandard.jpg',
        format: 'Standard Thumbnail',
        height: 75,
        width: 75,
        type: 'image',
        subtype: 'photo',
        caption:
          'Phil Valentine, a conservative radio show host, recording a podcast with his adult son, Campbell, in 2019.',
        copyright: 'Shelley Mays/The Tennessean',
      },
      {
        url: 'https://static01.nyt.com/images/2021/07/25/lens/25nashville-photo/25nashville-photo-thumbLarge.jpg',
        format: 'thumbLarge',
        height: 150,
        width: 150,
        type: 'image',
        subtype: 'photo',
        caption:
          'Phil Valentine, a conservative radio show host, recording a podcast with his adult son, Campbell, in 2019.',
        copyright: 'Shelley Mays/The Tennessean',
      },
      {
        url: 'https://static01.nyt.com/images/2021/07/25/lens/25nashville-photo/25nashville-photo-mediumThreeByTwo210.jpg',
        format: 'mediumThreeByTwo210',
        height: 140,
        width: 210,
        type: 'image',
        subtype: 'photo',
        caption:
          'Phil Valentine, a conservative radio show host, recording a podcast with his adult son, Campbell, in 2019.',
        copyright: 'Shelley Mays/The Tennessean',
      },
      {
        url: 'https://static01.nyt.com/images/2021/07/25/lens/25nashville-photo/25nashville-photo-articleInline.jpg',
        format: 'Normal',
        height: 127,
        width: 190,
        type: 'image',
        subtype: 'photo',
        caption:
          'Phil Valentine, a conservative radio show host, recording a podcast with his adult son, Campbell, in 2019.',
        copyright: 'Shelley Mays/The Tennessean',
      },
    ],
    short_url: 'https://nyti.ms/36ZZHhD',
  },
  {
    section: 'sports',
    subsection: 'olympics',
    title:
      'Broadcaster Apologizes for ‘Inappropriate’ Images Aired During Olympic Parade',
    abstract:
      'The South Korean broadcaster MBC showed photographs associating pizza with Italy, Chernobyl with Ukraine and Count Dracula with Romania in its coverage of the opening ceremony.',
    url: 'https://www.nytimes.com/2021/07/25/sports/olympics/mbc-broadcaster-apology-olympics-opening-ceremony.html',
    uri: 'nyt://article/aad9037f-d588-5dfd-90b6-a381d8e103e2',
    byline: 'By Neil Vigdor',
    item_type: 'Article',
    updated_date: '2021-07-26T10:51:05-04:00',
    created_date: '2021-07-25T17:52:43-04:00',
    published_date: '2021-07-25T17:52:43-04:00',
    material_type_facet: '',
    kicker: '',
    des_facet: [
      'Olympic Games (2022)',
      'International Relations',
      'News and News Media',
      'Parades',
      'Apologies',
      'Discrimination',
    ],
    org_facet: ['Munhwa Broadcasting Corporation'],
    per_facet: [],
    geo_facet: ['South Korea'],
    multimedia: [
      {
        url: 'https://static01.nyt.com/images/2021/07/25/sports/oakImage-1627244037245/oakImage-1627244037245-superJumbo.jpg',
        format: 'superJumbo',
        height: 390,
        width: 700,
        type: 'image',
        subtype: 'photo',
        caption:
          'When the contingent of Olympic athletes from Italy entered Tokyo’s Olympic Stadium for the parade of nations, the broadcaster MBC aired a photo of a pizza.',
        copyright: '',
      },
      {
        url: 'https://static01.nyt.com/images/2021/07/25/sports/oakImage-1627244037245/oakImage-1627244037245-thumbStandard.jpg',
        format: 'Standard Thumbnail',
        height: 75,
        width: 75,
        type: 'image',
        subtype: 'photo',
        caption:
          'When the contingent of Olympic athletes from Italy entered Tokyo’s Olympic Stadium for the parade of nations, the broadcaster MBC aired a photo of a pizza.',
        copyright: '',
      },
      {
        url: 'https://static01.nyt.com/images/2021/07/25/sports/oakImage-1627244037245/oakImage-1627244037245-thumbLarge.jpg',
        format: 'thumbLarge',
        height: 150,
        width: 150,
        type: 'image',
        subtype: 'photo',
        caption:
          'When the contingent of Olympic athletes from Italy entered Tokyo’s Olympic Stadium for the parade of nations, the broadcaster MBC aired a photo of a pizza.',
        copyright: '',
      },
      {
        url: 'https://static01.nyt.com/images/2021/07/25/sports/oakImage-1627244037245/oakImage-1627244037245-mediumThreeByTwo210.jpg',
        format: 'mediumThreeByTwo210',
        height: 140,
        width: 210,
        type: 'image',
        subtype: 'photo',
        caption:
          'When the contingent of Olympic athletes from Italy entered Tokyo’s Olympic Stadium for the parade of nations, the broadcaster MBC aired a photo of a pizza.',
        copyright: '',
      },
      {
        url: 'https://static01.nyt.com/images/2021/07/25/sports/oakImage-1627244037245/oakImage-1627244037245-articleInline.jpg',
        format: 'Normal',
        height: 106,
        width: 190,
        type: 'image',
        subtype: 'photo',
        caption:
          'When the contingent of Olympic athletes from Italy entered Tokyo’s Olympic Stadium for the parade of nations, the broadcaster MBC aired a photo of a pizza.',
        copyright: '',
      },
    ],
    short_url: 'https://nyti.ms/3y488Va',
  },
  {
    section: 'technology',
    subsection: '',
    title: 'The Most Influential Spreader of Coronavirus Misinformation Online',
    abstract:
      'Researchers and regulators say Joseph Mercola, an osteopathic physician, creates and profits from misleading claims about Covid-19 vaccines.',
    url: 'https://www.nytimes.com/2021/07/24/technology/joseph-mercola-coronavirus-misinformation-online.html',
    uri: 'nyt://article/fcde30a2-f609-531f-b5c9-8e7df51a2f44',
    byline: 'By Sheera Frenkel',
    item_type: 'Article',
    updated_date: '2021-07-26T16:01:41-04:00',
    created_date: '2021-07-24T09:53:01-04:00',
    published_date: '2021-07-24T09:53:01-04:00',
    material_type_facet: '',
    kicker: '',
    des_facet: [
      'Coronavirus (2019-nCoV)',
      'Vaccination and Immunization',
      'Rumors and Misinformation',
      'Social Media',
      'Content Type: Personal Profile',
    ],
    org_facet: [],
    per_facet: ['Mercola, Joseph M (1954- )', 'Elizabeth, Erin'],
    geo_facet: [],
    multimedia: [
      {
        url: 'https://static01.nyt.com/images/2021/07/22/business/00mercola/00mercola-superJumbo.jpg',
        format: 'superJumbo',
        height: 2048,
        width: 1366,
        type: 'image',
        subtype: 'photo',
        caption:
          'Joseph Mercola, an osteopathic physician in Cape Coral, Fla., is a key figure in the “Disinformation Dozen” spreading anti-vaccine messaging, researchers said.',
        copyright: 'Mercola',
      },
      {
        url: 'https://static01.nyt.com/images/2021/07/22/business/00mercola/00mercola-thumbStandard.jpg',
        format: 'Standard Thumbnail',
        height: 75,
        width: 75,
        type: 'image',
        subtype: 'photo',
        caption:
          'Joseph Mercola, an osteopathic physician in Cape Coral, Fla., is a key figure in the “Disinformation Dozen” spreading anti-vaccine messaging, researchers said.',
        copyright: 'Mercola',
      },
      {
        url: 'https://static01.nyt.com/images/2021/07/22/business/00mercola/00mercola-thumbLarge.jpg',
        format: 'thumbLarge',
        height: 150,
        width: 150,
        type: 'image',
        subtype: 'photo',
        caption:
          'Joseph Mercola, an osteopathic physician in Cape Coral, Fla., is a key figure in the “Disinformation Dozen” spreading anti-vaccine messaging, researchers said.',
        copyright: 'Mercola',
      },
      {
        url: 'https://static01.nyt.com/images/2021/07/22/business/00mercola/00mercola-mediumThreeByTwo210.jpg',
        format: 'mediumThreeByTwo210',
        height: 140,
        width: 210,
        type: 'image',
        subtype: 'photo',
        caption:
          'Joseph Mercola, an osteopathic physician in Cape Coral, Fla., is a key figure in the “Disinformation Dozen” spreading anti-vaccine messaging, researchers said.',
        copyright: 'Mercola',
      },
      {
        url: 'https://static01.nyt.com/images/2021/07/22/business/00mercola/00mercola-articleInline.jpg',
        format: 'Normal',
        height: 285,
        width: 190,
        type: 'image',
        subtype: 'photo',
        caption:
          'Joseph Mercola, an osteopathic physician in Cape Coral, Fla., is a key figure in the “Disinformation Dozen” spreading anti-vaccine messaging, researchers said.',
        copyright: 'Mercola',
      },
    ],
    short_url: 'https://nyti.ms/3rv5mWt',
  },
  {
    section: 'well',
    subsection: 'live',
    title: 'A Common Heart Problem That’s Easy to Miss',
    abstract:
      'About three million adults in the U.S. have been diagnosed with A-fib, a heart-rhythm abnormality that’s on the rise. Here’s how to recognize the signs and treat it.',
    url: 'https://www.nytimes.com/2021/07/26/well/live/afib-warning-signs.html',
    uri: 'nyt://article/fa619040-9833-5742-af58-2855f87e4b61',
    byline: 'By Jane E. Brody',
    item_type: 'Article',
    updated_date: '2021-07-26T08:25:38-04:00',
    created_date: '2021-07-26T05:00:08-04:00',
    published_date: '2021-07-26T05:00:08-04:00',
    material_type_facet: '',
    kicker: 'Personal Health',
    des_facet: [
      'Preventive Medicine',
      'Content Type: Service',
      'Heart',
      'Tests (Medical)',
    ],
    org_facet: [],
    per_facet: [],
    geo_facet: [],
    multimedia: [
      {
        url: 'https://static01.nyt.com/images/2021/07/27/science/26sci-BRODY-AFIB/26sci-BRODY-AFIB-superJumbo.jpg',
        format: 'superJumbo',
        height: 1302,
        width: 1965,
        type: 'image',
        subtype: 'photo',
        caption: '',
        copyright: 'Gracia Lam',
      },
      {
        url: 'https://static01.nyt.com/images/2021/07/27/science/26sci-BRODY-AFIB/26sci-BRODY-AFIB-thumbStandard.jpg',
        format: 'Standard Thumbnail',
        height: 75,
        width: 75,
        type: 'image',
        subtype: 'photo',
        caption: '',
        copyright: 'Gracia Lam',
      },
      {
        url: 'https://static01.nyt.com/images/2021/07/27/science/26sci-BRODY-AFIB/26sci-BRODY-AFIB-thumbLarge.jpg',
        format: 'thumbLarge',
        height: 150,
        width: 150,
        type: 'image',
        subtype: 'photo',
        caption: '',
        copyright: 'Gracia Lam',
      },
      {
        url: 'https://static01.nyt.com/images/2021/07/27/science/26sci-BRODY-AFIB/26sci-BRODY-AFIB-mediumThreeByTwo210.jpg',
        format: 'mediumThreeByTwo210',
        height: 140,
        width: 210,
        type: 'image',
        subtype: 'photo',
        caption: '',
        copyright: 'Gracia Lam',
      },
      {
        url: 'https://static01.nyt.com/images/2021/07/27/science/26sci-BRODY-AFIB/26sci-BRODY-AFIB-articleInline.jpg',
        format: 'Normal',
        height: 126,
        width: 190,
        type: 'image',
        subtype: 'photo',
        caption: '',
        copyright: 'Gracia Lam',
      },
    ],
    short_url: 'https://nyti.ms/3eY5atD',
  },
];
